### ISSUE TITLE
MMM-Notion: Could not find database with ID

### ISSUE THREAD

**Issue by FriedrichUthe** [choffmann/MMM-Notion#1]
Hi choffmann,

can you please help? 

I receive this error log when trying to get your module to do some magic for me.

```
[11.04.2023 07:35.42.517] [WARN]  @notionhq/client warn: request fail {
  code: 'object_not_found',
  message: 'Could not find database with ID: c7b143a7-21b3-4f55-bfcb-c74b5d243c9 1. Make sure the relevant pages and databases are shared with your integration.'
}
[11.04.2023 07:35.42.526] [ERROR] APIResponseError: Could not find database with ID: c7b143a7-21b3-4f55-bfcb-c74b5d243c91. Make sure the relevant pages and databases are shared with your integration.
    at buildRequestError (/home/fwuth/MagicMirror/modules/MMM-Notion/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/home/fwuth/MagicMirror/modules/MMM-Notion/node_modules/@notionhq/client/build/src/Client.js:304:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Class.makeQuery (/home/fwuth/MagicMirror/modules/MMM-Notion/node_helper.js:43:10)
    at async Class.makeRequest (/home/fwuth/MagicMirror/modules/MMM-Notion/node_helper.js:32:18)
    at async Class.socketNotificationReceived (/home/fwuth/MagicMirror/modules/MMM-Notion/node_helper.js:20:5) {
  code: 'object_not_found',
  status: 404,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'transfer-encoding': [Array],
      connection: [Array],
      'set-cookie': [Array],
      'content-security-policy': [Array],
      'x-dns-prefetch-control': [Array],
      'x-frame-options': [Array],
      'strict-transport-security': [Array],
      'x-download-options': [Array],
      'x-content-type-options': [Array],
      'x-permitted-cross-domain-policies': [Array],
      'referrer-policy': [Array],
      'x-xss-protection': [Array],
      etag: [Array],
      vary: [Array],
      'cf-cache-status': [Array],
      server: [Array],
      'cf-ray': [Array],
      'content-encoding': [Array]
    }
  },
  body: '{"object":"error","status":404,"code":"object_not_found","message":"Could not find database with ID: c7b143a7-21b3-4f55-bfcb-c74b5d243c91. Make sure the relevant pages and databases are shared with your integration."}'

```

According to the error the database cannot be found. I think I configured it correctly though:

![grafik](https://user-images.githubusercontent.com/52453441/231069566-02dac6c1-b9a6-4334-af4c-1fcb1270edfe.png)

There are hyphons inserted in the error-log (not in the config-file). 
Might they be problematic?

Thanks in advance,
Fritz

PS:Just tried to add a notion database instead of a simple notion page.  The result is pretty much the same, just with a different ID.

**Comment by choffmann** [comment]
Hi @FriedrichUthe, so far, everything looks good. Yes it is correct that there are no hyphens in the configuration file. Can you go through the documentation of Notion (point 1 to 3 until you have the databse-id https://developers.notion.com/docs/create-a-notion-integration). If the problem still persists, I'll take another look at the code.

**Comment by FriedrichUthe** [comment]
I tried to reproduce with a new database and now it seems to work. No idea what was wrong the first time. Thanks!
